### ISSUE TITLE
输入为 YUV420P10, YUV420P16 时，非字幕部分的像素值改变

### ISSUE THREAD

**Issue by sinsanction** [computerfan/VSFilterMod#2]
在16b下进行渲染时，发现非字幕部分的像素值有变化，即使是完全没有字幕的帧也会受到影响，变化在数百左右。

10b下存在同样问题，变化在+-3左右。

8b下未发现问题。

问题普遍能复现且与字幕无关，就不提供样例了，你可以随便找个字幕在16b下测试。

希望能解决这个问题，感谢！

**Comment by computerfan** [comment]
修了，你可以测试下。我随手试了几个颜色应该没啥问题。

**Comment by sinsanction** [comment]
没问题了，感谢

**Comment by Masaiki** [comment]
NB，当时排查了好一会儿都没找到
